/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package a4_client.gui;

import com.a4.javawebservice.client.Client;
import com.a4.javawebservice.client.ClientOperationsWebService;
import com.a4.javawebservice.client.User;
import javax.swing.JFrame;

/**
 *
 * @author radud
 */
public class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initTheme();
        initComponents();
        myInit();
    }

    public void initTheme() {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    private void myInit() {
        clientProxy = (new Client()).getClientOperationsWebServicePort();

        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        registerForm.setLocationRelativeTo(this);
        registerForm.setResizable(false);
        registerForm.setVisible(false);
        registerForm.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        errorText.setVisible(false);
    }

    private void showRegisterForm() {
        registerUsernameField.setText("");
        registerPasswordField1.setText("");
        registerPasswordField2.setText("");
        registerFullNameField.setText("");
        registerErrorLabel.setVisible(false);
        registerForm.setVisible(true);
        registerForm.setLocationRelativeTo(this);
    }

    private void showClientForm(User user) {
        if (user.isAdmin()) {
            return;
        }
        ClientForm clientForm = new ClientForm(user);
        clientForm.setVisible(true);
        closeCurrentFrame();
    }

    private void showAdminForm(User user) {
        if (!user.isAdmin()) {
            return;
        }
        AdminForm adminForm = new AdminForm(user.getId());
        adminForm.setVisible(true);
        closeCurrentFrame();
    }

    private void closeCurrentFrame() {
        setVisible(false);
        registerForm.setVisible(false);
        dispose();
    }

    private void login(String username, String password) {
        User user = clientProxy.login(username, password);

        if (user != null) {
            if (user.isAdmin()) {
                showAdminForm(user);
            } else {
                showClientForm(user);
            }
        } else {
            errorText.setVisible(true);
            errorText.setText("Please verify your username and password and try again.");
        }
    }

    private void register(User user) {

        if (user == null) {
            return;
        }

        int id = clientProxy.register(user);
        if (id == -1) {
            registerErrorLabel.setVisible(true);
            registerErrorLabel.setText("There was a problem registering you. Please try again.");
            return;
        } else {
            user.setId(id);
        }

        if (user.isAdmin()) {
            showAdminForm(user);
        } else {
            showClientForm(user);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registerForm = new javax.swing.JFrame();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        registerDoneButton = new javax.swing.JButton();
        registerUsernameField = new javax.swing.JTextField();
        registerPasswordField1 = new javax.swing.JPasswordField();
        registerPasswordField2 = new javax.swing.JPasswordField();
        registerFullNameField = new javax.swing.JTextField();
        registerUsernameLabel = new javax.swing.JLabel();
        registerPassword1Label = new javax.swing.JLabel();
        registerPassword2Label = new javax.swing.JLabel();
        registerFullNameLabel = new javax.swing.JLabel();
        registerErrorLabel = new javax.swing.JLabel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        loginButton = new javax.swing.JButton();
        errorText = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        registerButton = new javax.swing.JButton();

        registerForm.setMaximumSize(new java.awt.Dimension(450, 340));
        registerForm.setMinimumSize(new java.awt.Dimension(450, 340));
        registerForm.setPreferredSize(new java.awt.Dimension(450, 340));
        registerForm.setResizable(false);

        registerDoneButton.setText("Done");
        registerDoneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerDoneButtonActionPerformed(evt);
            }
        });

        registerUsernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerUsernameFieldActionPerformed(evt);
            }
        });

        registerUsernameLabel.setText("Username : ");

        registerPassword1Label.setText("Password : ");

        registerPassword2Label.setText("Repeat passwrod :");

        registerFullNameLabel.setText("Full name : ");

        registerErrorLabel.setForeground(new java.awt.Color(204, 0, 51));
        registerErrorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registerErrorLabel.setText("jLabel1");

        jDesktopPane2.setLayer(registerDoneButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(registerUsernameField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(registerPasswordField1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(registerPasswordField2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(registerFullNameField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(registerUsernameLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(registerPassword1Label, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(registerPassword2Label, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(registerFullNameLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(registerErrorLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(registerErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(registerFullNameLabel)
                            .addComponent(registerUsernameLabel)
                            .addComponent(registerPassword1Label)
                            .addComponent(registerPassword2Label))
                        .addGap(45, 45, 45)
                        .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(registerDoneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(registerUsernameField)
                                .addComponent(registerPasswordField1)
                                .addComponent(registerPasswordField2)
                                .addComponent(registerFullNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerUsernameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerPassword1Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerPassword2Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerFullNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerFullNameLabel))
                .addGap(29, 29, 29)
                .addComponent(registerErrorLabel)
                .addGap(18, 18, 18)
                .addComponent(registerDoneButton)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout registerFormLayout = new javax.swing.GroupLayout(registerForm.getContentPane());
        registerForm.getContentPane().setLayout(registerFormLayout);
        registerFormLayout.setHorizontalGroup(
            registerFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane2)
        );
        registerFormLayout.setVerticalGroup(
            registerFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 400));
        setResizable(false);
        setSize(new java.awt.Dimension(600, 400));

        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        errorText.setForeground(new java.awt.Color(204, 0, 0));
        errorText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errorText.setText("Error text");

        usernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameFieldActionPerformed(evt);
            }
        });

        usernameLabel.setText("Username :");

        passwordLabel.setText("Password :");

        registerButton.setText("Register");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(loginButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(errorText, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(usernameField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(usernameLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(passwordLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(passwordField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(registerButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(passwordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(usernameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                        .addGap(44, 44, 44)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(usernameField)
                            .addComponent(passwordField, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE))
                        .addGap(104, 104, 104))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110)
                        .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(145, 145, 145))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(errorText, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 23, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameLabel))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passwordLabel)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(errorText)
                .addGap(27, 27, 27)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginButton)
                    .addComponent(registerButton))
                .addGap(59, 59, 59))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed

        errorText.setVisible(false);

        String username = usernameField.getText();
        String password = passwordField.getText();

        if (!username.equals("") && !password.equals("")) {
            login(username, password);
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFieldActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        errorText.setVisible(false);
        showRegisterForm();
    }//GEN-LAST:event_registerButtonActionPerformed

    private void registerUsernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerUsernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerUsernameFieldActionPerformed

    private void registerDoneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerDoneButtonActionPerformed
        if (registerUsernameField.getText().equals("")) {
            registerErrorLabel.setVisible(true);
            registerErrorLabel.setText("Enter an username");
            return;
        }

        if (registerPasswordField1.getText().equals("")) {
            registerErrorLabel.setText("Enter a valid password");
            return;
        }

        if (registerPasswordField2.getText().equals("")) {
            registerErrorLabel.setText("Enter a valid password");
            return;
        }

        if (registerFullNameField.getText().equals("")) {
            registerErrorLabel.setText("Enter your full name");
            return;
        }

        if (!registerPasswordField2.getText().equals(registerPasswordField1.getText())) {
            registerErrorLabel.setText("Your passwords do not match");
            return;
        }

        String username = registerUsernameField.getText();
        String password = registerPasswordField1.getText();
        String fullName = registerFullNameField.getText();

        User user = new User();
        user.setUsername(username);
        user.setPassword(password);
        user.setFullName(fullName);

        register(user);
    }//GEN-LAST:event_registerDoneButtonActionPerformed

    ClientOperationsWebService clientProxy;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errorText;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JButton loginButton;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JButton registerButton;
    private javax.swing.JButton registerDoneButton;
    private javax.swing.JLabel registerErrorLabel;
    private javax.swing.JFrame registerForm;
    private javax.swing.JTextField registerFullNameField;
    private javax.swing.JLabel registerFullNameLabel;
    private javax.swing.JLabel registerPassword1Label;
    private javax.swing.JLabel registerPassword2Label;
    private javax.swing.JPasswordField registerPasswordField1;
    private javax.swing.JPasswordField registerPasswordField2;
    private javax.swing.JTextField registerUsernameField;
    private javax.swing.JLabel registerUsernameLabel;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
